#!/usr/bin/env python3
"""Analyze a recorded WAV/FLAC and compare against artist references.

Usage:  uv run --with librosa --with numpy tools/analyze-wav.py <wav-file>

Outputs BPM, key, spectral centroid, spectral flatness, onset density,
dynamic range, and an RMS curve. Compares against pre-analysed reference
tracks from the user's collection.
"""

import sys
import json
import numpy as np
import librosa

# Generated by tools/batch-analyze.py — 33 tracks across 5 artists.
# Re-run that script to refresh after adding more reference albums.
REFERENCES = {
    # Bonobo · Black Sands (2010)
    "Bonobo · Prelude":         {"bpm": 184.6, "key": "F",  "centroid": 1638, "flatness": 0.0134, "dyn_x":    3.9, "onsets_per_s": 1.28, "rms_min": 0.0684, "rms_max": 0.2677},
    "Bonobo · Kong":            {"bpm":  95.7, "key": "F#", "centroid": 1980, "flatness": 0.0153, "dyn_x":    5.5, "onsets_per_s": 4.26, "rms_min": 0.0508, "rms_max": 0.2779},
    "Bonobo · Eyesdown":        {"bpm":  64.6, "key": "B",  "centroid": 1998, "flatness": 0.0198, "dyn_x":    5.7, "onsets_per_s": 3.42, "rms_min": 0.0486, "rms_max": 0.2795},
    "Bonobo · 1009":            {"bpm": 129.2, "key": "C#", "centroid": 2800, "flatness": 0.0393, "dyn_x":    3.8, "onsets_per_s": 4.56, "rms_min": 0.0743, "rms_max": 0.2820},
    "Bonobo · Animals":         {"bpm": 136.0, "key": "B",  "centroid": 1924, "flatness": 0.0123, "dyn_x":   16.2, "onsets_per_s": 4.08, "rms_min": 0.0187, "rms_max": 0.3033},
    "Bonobo · Black Sands":     {"bpm":  89.1, "key": "C",  "centroid": 1427, "flatness": 0.0300, "dyn_x": 2932.9, "onsets_per_s": 4.15, "rms_min": 0.0000, "rms_max": 0.2933},
    # DJRUM · Portrait with Firewood (2018) + Under Tangled Silence (2025)
    "DJRUM · Unblocked":        {"bpm": 129.2, "key": "A#", "centroid": 1516, "flatness": 0.0096, "dyn_x":  918.0, "onsets_per_s": 1.53, "rms_min": 0.0002, "rms_max": 0.2277},
    "DJRUM · Creature Pt.1":    {"bpm":  99.4, "key": "D#", "centroid":  708, "flatness": 0.0014, "dyn_x":   15.9, "onsets_per_s": 1.43, "rms_min": 0.0188, "rms_max": 0.2983},
    "DJRUM · Creature Pt.2":    {"bpm": 172.3, "key": "D",  "centroid": 1720, "flatness": 0.0111, "dyn_x":   11.7, "onsets_per_s": 3.98, "rms_min": 0.0335, "rms_max": 0.3908},
    "DJRUM · Sex":              {"bpm":  89.1, "key": "F#", "centroid": 2543, "flatness": 0.0144, "dyn_x":    4.9, "onsets_per_s": 6.77, "rms_min": 0.0932, "rms_max": 0.4561},
    "DJRUM · Reprise":          {"bpm": 129.2, "key": "E",  "centroid":  858, "flatness": 0.0005, "dyn_x":   56.6, "onsets_per_s": 1.18, "rms_min": 0.0030, "rms_max": 0.1715},
    "DJRUM · Waxcap":           {"bpm":  89.1, "key": "G",  "centroid": 1926, "flatness": 0.0106, "dyn_x":   10.4, "onsets_per_s": 5.16, "rms_min": 0.0390, "rms_max": 0.4047},
    "DJRUM · Hold":             {"bpm": 112.3, "key": "C",  "centroid": 1117, "flatness": 0.0032, "dyn_x":    9.1, "onsets_per_s": 4.66, "rms_min": 0.0156, "rms_max": 0.1418},
    # Floating Points · Crush, Cascade, Reflections
    "Floating Pts · Last Bloom":{"bpm": 107.7, "key": "C",  "centroid": 1454, "flatness": 0.0074, "dyn_x":    5.5, "onsets_per_s": 5.80, "rms_min": 0.0513, "rms_max": 0.2837},
    "Floating Pts · LesAlpx":   {"bpm": 129.2, "key": "F",  "centroid": 1587, "flatness": 0.0075, "dyn_x":   12.5, "onsets_per_s": 5.69, "rms_min": 0.0310, "rms_max": 0.3861},
    "Floating Pts · Requiem":   {"bpm":  56.2, "key": "D#", "centroid":  783, "flatness": 0.0027, "dyn_x":   19.9, "onsets_per_s": 1.94, "rms_min": 0.0174, "rms_max": 0.3447},
    "Floating Pts · Birth4000": {"bpm": 129.2, "key": "F",  "centroid": 2607, "flatness": 0.0415, "dyn_x": 1096.0, "onsets_per_s": 7.12, "rms_min": 0.0005, "rms_max": 0.4968},
    "Floating Pts · Afflecks":  {"bpm":  73.8, "key": "A#", "centroid": 2115, "flatness": 0.0189, "dyn_x":  196.2, "onsets_per_s": 5.14, "rms_min": 0.0021, "rms_max": 0.4188},
    "Floating Pts · Mojave":    {"bpm": 123.0, "key": "B",  "centroid": 1124, "flatness": 0.0037, "dyn_x":   24.9, "onsets_per_s": 0.36, "rms_min": 0.0091, "rms_max": 0.2271},
    "Floating Pts · Kelso":     {"bpm": 172.3, "key": "A#", "centroid": 1609, "flatness": 0.0067, "dyn_x":   21.1, "onsets_per_s": 2.83, "rms_min": 0.0159, "rms_max": 0.3352},
    # Kiasmos · Kiasmos (2014)
    "Kiasmos · Lit":            {"bpm": 117.5, "key": "G",  "centroid": 1474, "flatness": 0.0166, "dyn_x":   15.2, "onsets_per_s": 2.49, "rms_min": 0.0209, "rms_max": 0.3169},
    "Kiasmos · Held":           {"bpm":  56.2, "key": "G",  "centroid":  993, "flatness": 0.0023, "dyn_x":  109.6, "onsets_per_s": 2.06, "rms_min": 0.0027, "rms_max": 0.3000},
    "Kiasmos · Looped":         {"bpm": 117.5, "key": "G",  "centroid": 1008, "flatness": 0.0029, "dyn_x":    7.4, "onsets_per_s": 3.75, "rms_min": 0.0459, "rms_max": 0.3411},
    "Kiasmos · Swayed":         {"bpm": 123.0, "key": "F",  "centroid": 1178, "flatness": 0.0076, "dyn_x":    3.2, "onsets_per_s": 5.60, "rms_min": 0.0932, "rms_max": 0.2967},
    "Kiasmos · Thrown":         {"bpm": 117.5, "key": "F",  "centroid": 1033, "flatness": 0.0024, "dyn_x":   19.3, "onsets_per_s": 2.98, "rms_min": 0.0150, "rms_max": 0.2891},
    "Kiasmos · Bent":           {"bpm": 123.0, "key": "E",  "centroid": 1153, "flatness": 0.0059, "dyn_x":  186.7, "onsets_per_s": 4.93, "rms_min": 0.0017, "rms_max": 0.3114},
    # Skee Mask · Compro, Pool, Resort
    "Skee Mask · Rev8617":      {"bpm": 107.7, "key": "F#", "centroid": 1484, "flatness": 0.0117, "dyn_x":    8.6, "onsets_per_s": 6.24, "rms_min": 0.0362, "rms_max": 0.3106},
    "Skee Mask · Flyby VFR":    {"bpm": 136.0, "key": "E",  "centroid": 2100, "flatness": 0.0239, "dyn_x":  272.9, "onsets_per_s": 4.83, "rms_min": 0.0011, "rms_max": 0.3123},
    "Skee Mask · Via Sub Mids": {"bpm":  73.8, "key": "G",  "centroid": 1237, "flatness": 0.0079, "dyn_x":  100.0, "onsets_per_s": 6.12, "rms_min": 0.0038, "rms_max": 0.3756},
    "Skee Mask · LFO":          {"bpm": 143.6, "key": "G#", "centroid": 2066, "flatness": 0.0119, "dyn_x":   14.1, "onsets_per_s": 2.26, "rms_min": 0.0201, "rms_max": 0.2837},
    "Skee Mask · Breathing":    {"bpm": 112.3, "key": "G#", "centroid": 2052, "flatness": 0.0204, "dyn_x":    2.2, "onsets_per_s": 6.62, "rms_min": 0.1394, "rms_max": 0.3000},
    "Skee Mask · Element":      {"bpm": 112.3, "key": "E",  "centroid": 1401, "flatness": 0.0075, "dyn_x":    5.0, "onsets_per_s": 4.26, "rms_min": 0.0595, "rms_max": 0.2998},
    "Skee Mask · 7AM Rodeo":    {"bpm": 117.5, "key": "A#", "centroid": 1226, "flatness": 0.0043, "dyn_x":  100.9, "onsets_per_s": 5.99, "rms_min": 0.0025, "rms_max": 0.2474},
}

KEYS = ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"]

def analyze(path):
    y, sr = librosa.load(path, sr=22050, mono=True)
    dur = librosa.get_duration(y=y, sr=sr)
    tempo, _ = librosa.beat.beat_track(y=y, sr=sr)
    tempo = float(np.atleast_1d(tempo)[0])
    hop = sr * 5
    rms = librosa.feature.rms(y=y, frame_length=hop, hop_length=hop)[0]
    sc = librosa.feature.spectral_centroid(y=y, sr=sr)[0].mean()
    chroma = librosa.feature.chroma_cqt(y=y, sr=sr).mean(axis=1)
    flatness = librosa.feature.spectral_flatness(y=y).mean()
    onsets = librosa.onset.onset_detect(y=y, sr=sr, units="time")
    return {
        "duration_s": round(float(dur), 1),
        "bpm": round(tempo, 1),
        "key": KEYS[int(np.argmax(chroma))],
        "centroid_hz": round(float(sc), 0),
        "spectral_flatness": round(float(flatness), 4),
        "onsets_per_second": round(len(onsets) / max(dur, 0.01), 2),
        "rms_min": round(float(rms.min()), 4),
        "rms_max": round(float(rms.max()), 4),
        "dynamic_ratio_x": round(float(rms.max()) / max(float(rms.min()), 0.0001), 1),
        "rms_curve_5s": [round(float(x), 4) for x in rms],
    }

def closest_ref(metric_name, value):
    """Find the reference track closest to `value` on `metric_name`."""
    candidates = [(k, v.get(metric_name)) for k, v in REFERENCES.items() if v.get(metric_name) is not None]
    if not candidates:
        return None
    return min(candidates, key=lambda kv: abs(kv[1] - value))

def critique(stats):
    lines = ["", "## Diagnosis vs references", ""]
    # Dynamic range — biggest discriminator
    dyn = stats["dynamic_ratio_x"]
    closest = closest_ref("dyn_x", dyn)
    if dyn < 10:
        lines.append(f"  ⚠ DYNAMIC RANGE LOW ({dyn}×). References sit at 5×–273×. Track sounds too compressed/flat.")
        lines.append("    → Drop voices in slot 1 and 8 (real quiet sections). Lift gains in climax slot.")
    else:
        lines.append(f"  ✓ Dynamic range OK ({dyn}×, near {closest[0]} at {closest[1]}×).")
    # Centroid — brightness
    c = stats["centroid_hz"]
    if c > 2200:
        lines.append(f"  ⚠ TOO BRIGHT ({c} Hz). References: 688–2100 Hz. Cut the high end on synths/hats.")
    elif c < 500:
        lines.append(f"  ⚠ TOO DARK ({c} Hz). References: 688+ Hz. Add presence — open filters, add a high voice.")
    else:
        cc = closest_ref("centroid", c)
        lines.append(f"  ✓ Spectral balance OK ({c} Hz, similar to {cc[0]} at {cc[1]} Hz).")
    # Flatness — tonal vs noisy
    f = stats["spectral_flatness"]
    if f > 0.05:
        lines.append(f"  ⚠ NOISY ({f:.3f}). Lots of high-flatness content (noise/granular). OK for Skee Mask; bad for Reprise-vibe.")
    elif f < 0.001:
        lines.append(f"  ✓ Purely tonal ({f:.4f}) — Reprise territory. No noise layers.")
    else:
        lines.append(f"  ✓ Flatness OK ({f:.4f}).")
    # Onsets — rhythmic density
    o = stats["onsets_per_second"]
    if o < 1:
        lines.append(f"  ⚠ Sparse rhythm ({o}/s). Could be intentional, but check vs intent.")
    elif o > 5:
        lines.append(f"  ⚠ Very dense ({o}/s). Could be Skee Mask territory; could just be cluttered.")
    else:
        lines.append(f"  ✓ Rhythmic density reasonable ({o}/s).")
    return "\n".join(lines)

def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)
    path = sys.argv[1]
    stats = analyze(path)
    print(json.dumps(stats, indent=2))
    print(critique(stats))

if __name__ == "__main__":
    main()
