#!/usr/bin/env python3
"""Build references/analysis/INDEX.md — a navigational summary of every analysis
card: per-skill tables (tempo, bass/melody key, dynamics, section count, chords)
with links to each card. Run after the cards exist.

    python3 tools/build-index.py
"""
import json
from collections import defaultdict
from pathlib import Path

OUT = Path("references/analysis")


def main() -> int:
    cards: dict[str, list] = defaultdict(list)
    for jp in sorted(OUT.rglob("*.json")):
        if "_cache" in jp.parts:
            continue
        cards[jp.parent.name].append((jp, json.loads(jp.read_text())))

    total = sum(len(v) for v in cards.values())
    lines = [
        "# Reference Analysis Index", "",
        f"{total} tracks · {len(cards)} artist-style skills. Generated by "
        "`tools/transcribe.py` (demucs stems → Basic Pitch → music21 DNA + librosa "
        "sections) with BTC large-vocabulary chords (`tools/augment_chords.py`).", "",
        "Each linked card has whole-track **bass + melody DNA** (key, register, "
        "interval histogram, octave-displacement), a **per-section** breakdown "
        "(time, loudness, brightness, chords, bass/melody Strudel `note(...)` seeds), "
        "and the chord progression.", "",
    ]
    for skill in sorted(cards):
        entries = sorted(cards[skill], key=lambda x: x[1]["label"])
        lines.append(f"## {skill} ({len(entries)})")
        lines.append("| Track | BPM | bass key | melody key | dyn | sects | chords |")
        lines.append("|---|---|---|---|---|---|---|")
        for jp, r in entries:
            s = r["stats"]
            v = r.get("voices", {})
            bk = (v.get("bass") or {}).get("key") or {}
            mk = (v.get("melody") or {}).get("key") or (v.get("full-mix") or {}).get("key") or {}
            rel = jp.with_suffix(".md").relative_to(OUT)
            label = r["label"].split("·")[-1].strip()
            prog = " ".join(r.get("chords", [])[:8])
            lines.append(
                f"| [{label}]({rel}) | {s['bpm']} | {bk.get('key', '—')} | "
                f"{mk.get('key', '—')} | {s['dyn_x']}× | {len(r.get('sections', []))} | {prog} |")
        lines.append("")

    (OUT / "INDEX.md").write_text("\n".join(lines))
    print(f"wrote {OUT / 'INDEX.md'} — {total} tracks across {len(cards)} skills")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
